# Generated by Django 3.0.7 on 2020-09-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_auto_20200928_1535'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='leavereportstudent',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
